version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: SITU_DATABASE
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@1234
      POSTGRES_DB: situ
    ports:
      - "5432:5432"
    volumes:
      - ./files/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
