spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/qa

spring.jpa.show-sql=false
logging.level.root=INFO

security.auth.refresh.cookie.secure=${AUTH_REFRESH_COOKIE_SECURE:true}
