spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/prod

spring.jpa.show-sql=false
logging.level.root=WARN

security.auth.refresh.cookie.secure=${AUTH_REFRESH_COOKIE_SECURE:true}
