spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/dev

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

security.cookie.secure=${COOKIE_SECURE:false}
