package com.backend.situ.enums;

public enum AuditAction {
    SIGNUP,
    LOGIN,
    CHANGE_PASSWORD,
    LOGOUT,
    NEW_COMPANY,
    NEW_ALERT,
    ALERT_UPDATED,
    ALERT_REMOVED,
    NEW_COMPLAINT,
    COMPLAINT_STATUS_UPDATED,
    COMPLAINT_ASSIGNED,
    COMPLAINT_REMOVED,
    USER_ROLE_UPDATE
}
